# Generated by Django 5.1.6 on 2025-03-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_neurouser_is_paid_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neurouser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
    ]
