# Generated by Django 5.1.7 on 2025-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscriptiontype_includes_subscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'ordering': ('name',), 'verbose_name': 'Тип подписки', 'verbose_name_plural': 'Типы подписок'},
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='includes_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='included_in', to='users.subscriptiontype'),
        ),
    ]
